root: true
parserOptions:
  ecmaVersion: 2020
env:
  node: true
  browser: true
  jasmine: true
  es6: true
plugins:
  - 'prettier'
extends:
  - 'google'
  - 'plugin:prettier/recommended'
rules:
  prettier/prettier: error
  require-jsdoc: 0
  new-cap: 0
  max-len:
    - 0
    - tabWidth: 2
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
overrides:
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'
      - 'prettier'
    extends:
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
      - 'google'
      - 'plugin:prettier/recommended'
    rules:
      prettier/prettier: error
      require-jsdoc: 0
      valid-jsdoc: 0
      new-cap: 0
      max-len:
        - 0
        - tabWidth: 2
          ignoreStrings: true
          ignoreTemplateLiterals: true
          ignoreRegExpLiterals: true
      '@typescript-eslint/no-explicit-any': 2
      '@typescript-eslint/explicit-function-return-type': 0
      '@typescript-eslint/no-unused-vars':
        - 1
        - argsIgnorePattern: '^_'
